### ISSUE TITLE
Request for implementation

### ISSUE THREAD

**Issue by satyakisikdar** [deezer/fastgae#1]
Hi authors,

I enjoyed reading the pre-print. Do you have a timeline in mind for releasing the implementation?

Thanks,
Satyaki

**Comment by GuillaumeSalhaGalvan** [comment]
Dear @satyakisikdar,

Thank you very much for your feedback!

We originally wanted to wait for the paper's official reviews before releasing the code. But we already received two resquests, so we will probably release it by the end of March.

We will keep you informed.

Best regards,


Guillaume

**Comment by GuillaumeSalhaGalvan** [comment]
Dear @satyakisikdar,

The code is now available!

Best regards,

Guillaume

**Comment by satyakisikdar** [comment]
Thank you, @GuillaumeSalha!
